# generated by maixhub, tested on maixpy3 v0.4.8
# copy files to TF card and plug into board and power on
import sensor, image, lcd, time
import KPU as kpu
from machine import UART
import gc, sys
from fpioa_manager import fm

input_size = (224, 224)
labels = ['4', '5', '7', 'c', 't', '1', '2', '3', '6', '8', 'r']
anchors = [1.59, 2.22, 1.22, 1.75, 1.53, 1.59, 1.41, 2.0, 1.88, 2.38]

def lcd_show_except(e):
    import uio
    err_str = uio.StringIO()
    sys.print_exception(e, err_str)
    err_str = err_str.getvalue()
    img = image.Image(size=input_size)
    img.draw_string(0, 10, err_str, scale=1, color=(0xff,0x00,0x00))
    lcd.display(img)

class Comm:
    def __init__(self, uart):
        self.uart = uart

        self.class_map = {
            'c':(0x00, 0x01),
            'r':(0x00, 0x02),
            't':(0x00, 0x03),

            '1':(0x01, 0x00),
            '2':(0x02, 0x00),
            '3':(0x03, 0x00),
            '4':(0x04, 0x00),
            '5':(0x05, 0x00),
            '6':(0x06, 0x00),
            '7':(0x07, 0x00),
            '8':(0x08, 0x00),

        }

    def send_detect_result(self, objects, labels):
        if not objects:
            return

        for obj in objects:
            # 获取识别到的标签名称
            idx = obj.classid()
            if idx < len(labels):
                label_name = labels[idx]
            else:
                continue

            # 查表获取对应的 数字值 和 图形值
            # 如果标签不在表里，默认发送 (0x00, 0x00)
            data_values = self.class_map.get(label_name, (0x00, 0x00))

            num_val = data_values[0]   # 对应第二个字节 (数字)
            shape_val = data_values[1] # 对应第三个字节 (图形)

            # [帧头0xAA, 数字, 图形, 帧尾0x0D]
            packet = bytearray([0xAA, num_val, shape_val, 0x0D])

            # 调试打印
            #print("UART DEBUG:", [hex(x) for x in packet])

            # 发送
            self.uart.write(packet)
            #uart.write(packet)

'''
    def send_detect_result(self, objects, labels):
        msg = ""
        for obj in objects:
            pos = obj.rect()
            p = obj.value()
            idx = obj.classid()
            label = labels[idx]
            msg += "{}:{}:{}:{}:{}:{:.2f}:{}, ".format(pos[0], pos[1], pos[2], pos[3], idx, p, label)
        if msg:
            msg = msg[:-2] + "\n"
        self.uart.write(msg.encode())
'''

def init_uart():
    fm.register(10, fm.fpioa.UART1_TX, force=True)
    fm.register(11, fm.fpioa.UART1_RX, force=True)

    uart = UART(UART.UART1, 115200, 8, 0, 0, timeout=1000, read_buf_len=256)
    return uart

def main(anchors, labels = None, model_addr="/sd/m.kmodel", sensor_window=input_size, lcd_rotation=0, sensor_hmirror=False, sensor_vflip=False):
    sensor.reset()
    sensor.set_pixformat(sensor.RGB565)
    sensor.set_framesize(sensor.QVGA)
    sensor.set_windowing(sensor_window)
    sensor.set_hmirror(False)
    sensor.set_vflip(True)
    sensor.run(1)

    lcd.init(type=1)
    lcd.rotation(0)
    lcd.clear(lcd.WHITE)

    if not labels:
        with open('labels.txt','r') as f:
            exec(f.read())
    if not labels:
        print("no labels.txt")
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "no labels.txt", color=(255, 0, 0), scale=2)
        lcd.display(img)
        return 1
    try:
        img = image.Image("startup.jpg")
        lcd.display(img)
    except Exception:
        img = image.Image(size=(320, 240))
        img.draw_string(90, 110, "loading model...", color=(255, 255, 255), scale=2)
        lcd.display(img)

    uart = init_uart()
    comm = Comm(uart)

    try:
        task = None
        task = kpu.load(model_addr)
        kpu.init_yolo2(task, 0.5, 0.3, 5, anchors) # threshold:[0,1], nms_value: [0, 1]
        while(True):
            img = sensor.snapshot()
            t = time.ticks_ms()
            objects = kpu.run_yolo2(task, img)
            t = time.ticks_ms() - t
            if objects:
                for obj in objects:
                    pos = obj.rect()
                    img.draw_rectangle(pos)
                    img.draw_string(pos[0], pos[1], "%s : %.2f" %(labels[obj.classid()], obj.value()), scale=2, color=(255, 0, 0))
                comm.send_detect_result(objects, labels)
            img.draw_string(0, 200, "t:%dms" %(t), scale=2, color=(255, 0, 0))
            #img.draw_string(0, 2, "Upgrade to MaixCAM to use YOLOv8", scale=1.2, color=(255, 0, 0))
            #img.draw_string(0, 30, "wiki.sipeed.com/maixcam", scale=1.2, color=(255, 0, 0))
            lcd.display(img)
    except Exception as e:
        raise e
    finally:
        if not task is None:
            kpu.deinit(task)


if __name__ == "__main__":
    try:
        # main(anchors = anchors, labels=labels, model_addr=0x300000, lcd_rotation=0)
        main(anchors = anchors, labels=labels, model_addr="/sd/model-245385.kmodel")
    except Exception as e:
        sys.print_exception(e)
        lcd_show_except(e)
    finally:
        gc.collect()
